# Introducción a NumPy

NumPy es una biblioteca fundamental para la computación científica en Python. Proporciona estructuras de datos eficientes y funcionalidad matemática para trabajar con arrays multidimensionales.

En este notebook, exploraremos los conceptos básicos de NumPy, incluyendo cómo crear arrays, realizar operaciones matemáticas y manipular datos.

## Contenido

1. Instalación
2. Importación de NumPy
3. Creación de Arrays
   - Arrays desde listas
   - Arrays con valores inicializados
4. Atributos de los Arrays
5. Operaciones Básicas
6. Indexación y Slicing
7. Manipulación de Arrays
   - Redimensionamiento
   - Concatenación y Apilamiento
8. Funciones Universales (ufuncs)
9. Operaciones Estadísticas
10. Máscaras y Filtros
11. Conclusión


## Instalación

Si aún no tienes NumPy instalado, puedes instalarlo utilizando `pip`:

```bash
pip install numpy

In [ ]:
import numpy as np

## Creación de Arrays

### Arrays desde listas

Puedes crear un array de NumPy a partir de una lista de Python usando la función `np.array()`.

In [ ]:
# Lista de Python
lista = [1, 2, 3, 4, 5]

# Convertir a array de NumPy
arr = np.array(lista)

print(arr)

[1 2 3 4 5]


In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

arr2.__gt__(2)

array([[False, False,  True],
       [ True,  True,  True]])

Arrays con valores inicializados
NumPy proporciona funciones para crear arrays con valores iniciales específicos:

* np.zeros(shape): Crea un array lleno de ceros.
* np.ones(shape): Crea un array lleno de unos.
* np.full(shape, fill_value): Crea un array lleno de un valor específico.
* np.eye(N): Crea una matriz identidad de tamaño N.
* np.random.rand(shape): Crea un array con valores aleatorios entre 0 y 1.

In [ ]:
# Array de ceros
ceros = np.zeros((2, 3))
print("Array de ceros:\n", ceros)

Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Array de unos
unos = np.ones((3, 2))
print("Array de unos:\n", unos)

Array de unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
unosInt = unos.astype('int16')

In [ ]:
unosInt

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [ ]:
# Matriz identidad
identidad = np.eye(4)
print("Matriz identidad:\n", identidad)

Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Array aleatorio
aleatorio = np.random.rand(2, 2)
print("Array aleatorio:\n", aleatorio)

Array aleatorio:
 [[0.91923048 0.15856648]
 [0.04528748 0.11008246]]


## Atributos de los Arrays

### Los arrays de NumPy tienen varios atributos útiles:

+ ndarray.ndim: Número de dimensiones.
+ ndarray.shape: Dimensiones del array.
+ ndarray.size: Número total de elementos.
+ ndarray.dtype: Tipo de dato de los elementos.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Número de dimensiones:", arr.ndim)
print("Forma:", arr.shape)
print("Tamaño total:", arr.size)
print("Tipo de dato:", arr.dtype)

Array:
 [[1 2 3]
 [4 5 6]]
Número de dimensiones: 2
Forma: (2, 3)
Tamaño total: 6
Tipo de dato: int64


## Operaciones Básicas

#### Las operaciones aritméticas en arrays de NumPy se aplican elemento por elemento.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Suma
print("Suma:", a + b)

# Resta
print("Resta:", a - b)

# Multiplicación
print("Multiplicación:", a * b)

# División
print("División:", a / b)

Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


## Indexación y Slicing

#### Puedes acceder a elementos y slices de manera similar a las listas de Python y dataframes de pandas

![image](https://courses.spatialthoughts.com/images/python_foundation/pandas_axis.png)

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

# Acceder a un elemento
print("Elemento en (0, 1):", arr[0, 1])

# Acceder a una fila
print("Primera fila:", arr[0])

# Acceder a una columna
print("Segunda columna:", arr[:, 1])

# Slicing
print("Subarray:\n", arr[0:2, 1:3])

Elemento en (0, 1): 20
Primera fila: [10 20 30]
Segunda columna: [20 50]
Subarray:
 [[20 30]
 [50 60]]


## Manipulación de Arrays

#### Redimensionamiento
Puedes cambiar la forma de un array sin modificar sus datos con reshape()

In [ ]:
arr = np.arange(12)
print("Array original:", arr)

# Redimensionar a 3 filas y 4 columnas
arr_reshaped = arr.reshape(3, 4)
print("Array redimensionado:\n", arr_reshaped)

Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Array redimensionado:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Concatenación y Apilamiento

#### Puedes unir arrays usando funciones como concatenate(), vstack(), y hstack().

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenar verticalmente
print("Concatenación vertical:\n", np.vstack((a, b)))

# Concatenar horizontalmente
print("Concatenación horizontal:\n", np.hstack((a, b.T)))

Concatenación vertical:
 [[1 2]
 [3 4]
 [5 6]]
Concatenación horizontal:
 [[1 2 5]
 [3 4 6]]


## Funciones Universales (ufuncs)

#### Las ufuncs son funciones que se aplican elemento por elemento a los arrays.

In [ ]:
arr = np.array([0, np.pi / 2, np.pi])

# Funciones trigonométricas
print("Seno:", np.sin(arr))
print("Coseno:", np.cos(arr))

Seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Coseno: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


## Operaciones Estadísticas
#### Puedes calcular estadísticas básicas directamente en arrays.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Máximo:", arr.max())
print("Mínimo:", arr.min())
print("Suma:", arr.sum())
print("Media:", arr.mean())
print("Desviación estándar:", arr.std())

Máximo: 6
Mínimo: 1
Suma: 21
Media: 3.5
Desviación estándar: 1.707825127659933


También puedes especificar el eje (axis) para calcular estas estadísticas a lo largo de filas o columnas.

In [ ]:
# Suma por columnas
print("Suma por columnas:", arr.sum(axis=0))

# Suma por filas
print("Suma por filas:", arr.sum(axis=1))

Suma por columnas: [5 7 9]
Suma por filas: [ 6 15]


## Máscaras y Filtros

Puedes crear máscaras booleanas para filtrar datos.

In [ ]:
arr = np.array([10, 15, 20, 25, 30])

# Máscara para valores mayores que 20
mascara = arr > 20
print("Máscara:", mascara)

# Filtrar el array
print("Valores mayores que 20:", arr[mascara])

Máscara: [False False False  True  True]
Valores mayores que 20: [25 30]


In [ ]:
import numpy as np

# Crear un array de ejemplo
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Crear una máscara booleana que seleccione los valores mayores que 5
mask = arr > 5

# Cambiar los valores enmascarados (mayores que 5) por un nuevo valor, digamos -1
arr[mask] = -1

# Mostrar el array modificado
print(arr)


[[ 1  2  3]
 [ 4  5 -1]
 [-1 -1 -1]]


In [ ]:
a = np.where(arr > 4, 17, arr)

In [ ]:
a

array([[ 1,  2,  3],
       [ 4, 17, -1],
       [-1, -1, -1]])